"""add system_prompt to reporttemplate

Revision ID: e4da44753596
Revises: d270304652ad
Create Date: 2026-03-25 07:59:38.365508
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e4da44753596'
down_revision: Union[str, None] = 'd270304652ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reporttemplate', sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reporttemplate', 'system_prompt')
    # ### end Alembic commands ###
